import type { Metadata } from "next";
import "@/sass/globals.scss";
import Modal from "@/components/templates/Modal";
import Header from "@/components/organisms/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>
    <Modal />
    <Header />
    {children}
  </>
}
