import type { Metadata } from "next";
import "@/sass/globals.scss";
import StoreProvider from "@/lib/store/provider";
import styles from "./_layout.module.scss";
import NavigatingType from "@/components/atoms/NavigatingType";
import BodyCtrl from "@/modules/BodyCtrl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <StoreProvider>
        <BodyCtrl>
          <NavigatingType />
          {children}
          <div className={`${styles.globalBg}`}></div>
        </BodyCtrl>
      </StoreProvider>
    </html>
  )
}
