import type { Metadata } from "next";
import "@/sass/globals.scss";
import styles from "./_layout.module.scss";
import Footer from "@/components/organisms/Footer";
import Header from "@/app/(root)/(uni-lab)/components/organisms/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function UniLabLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>
    <div className={`${styles.root}`}>
      <Header />
      <div className={`${styles.container}`}>
        {children}
      </div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </div>
  </>
}
