import styles from "./_layout.module.scss";
import type { Metadata } from "next";
import "@/sass/globals.scss";
import Footer from "@/components/organisms/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function BaseLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className={`${styles.container}`}>
        {children}
      </div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </>
  )
}
