import type { Metadata } from "next";
import "@/sass/globals.scss";
import StoreProvider from "@/lib/store/provider";
import styles from "./_layout.module.scss";
import { zenKakuGothicNew_w400 } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${styles.html}`}>
      <body className={`${styles.body} ${zenKakuGothicNew_w400.className}`}>
        <div className={`${styles.globalBg}`}></div>
        <div className={`${styles.container}`}>
          <StoreProvider>
            {children}
          </StoreProvider>
        </div>
      </body>
    </html>
  )
}
