import type { Metadata } from "next";
import "@/sass/globals.scss";
import StoreProvider from "@/lib/store/provider";
import styles from "./layout.module.scss";
import { roboto, zenOldMincho_w400, zenOldMincho_w900 } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${styles.body} ${zenOldMincho_w400.className}`}>
        <div className={`${styles.globalBg}`}></div>
        <StoreProvider>
          {children}
          <h1 className={`${styles.head} ${zenOldMincho_w900.className}`}>
            Hello
          </h1>
          <p className={`${styles.test} ${roboto.className}`}>
            Last login: Tue Aug 13 21:27:01 on console<br />
            Plese Select App...
          </p>
        </StoreProvider>
      </body>
    </html>
  )
}
