name: Next.js Build & FTP Upload

on:
  pull_request:
    branches:
      - main
    types: [closed]

  repository_dispatch:
    types: [Newt_Manual_Deploy]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_LOCAL }}" > $GITHUB_WORKSPACE/.env.local

      - name: Build
        run: yarn build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./out/
          dangerous-clean-slate: true
